@url = http://localhost:5248

###
POST {{url}}/slots/test1
Content-Type: application/json
Authorization: Bearer

{
    "DoctorName":"Test1",
    "Date": "2023-02-22T06:30Z",
    "IsReserved": true,
    "Cost": 1.3
}

###
GET {{url}}/slots/test1
Content-Type: application/json


###
POST {{url}}/appointments/test1
Content-Type: application/json

{
    "PaitentName":"Test",
    "Date":"22/02/2023 04:30 pm"
}

###
GET {{url}}/appointments/test1
Content-Type: application/

###
POST {{url}}/login
Content-Type: application/json

{
    "UserName": "admin"
}