@url = http://localhost:5248

###
POST {{url}}/doctorsavailabilities
Content-Type: application/json

{
    "doctorName":"Test",
    "isReserved": false,
    "cost": 1.40
}

###
{
    "DoctorName":"Test",
    "DoctorId": "",
    "Date":"Today",
    "IsReserved": true,
    "Cost":1.00
}