@url = http://localhost:5248

###
POST {{url}}/slots/test1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuZXciOiJhZG1pbiIsImV4cCI6MTY4OTg0ODkyMCwiaXNzIjoiRG9jdG9yc19BcHBvaW50bWVudCIsImF1ZCI6IkRvY3RvcnNfQXBwb2ludG1lbnQifQ.IumjamxGOyF9n33iH2Y1fq_Ream9-0v9XUuxAofyg20
{
    "DoctorName":"Test1",
    "Date": "2023-02-22T06:30Z",
    "IsReserved": true,
    "Cost": 1.3
}

###
GET {{url}}/slots/test1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuZXciOiJhZG1pbiIsImV4cCI6MTY4OTg0ODkyMCwiaXNzIjoiRG9jdG9yc19BcHBvaW50bWVudCIsImF1ZCI6IkRvY3RvcnNfQXBwb2ludG1lbnQifQ.IumjamxGOyF9n33iH2Y1fq_Ream9-0v9XUuxAofyg20

###
POST {{url}}/appointments/test1
Content-Type: application/json

{
    "PaitentName":"Test",
    "Date":"22/02/2023 04:30 pm"
}

###
GET {{url}}/appointments/test1
Content-Type: application/json

###
GET {{url}}/authenticate

###
POST {{url}}/authenticate
Content-Type: application/json

{
    "UserName": "admin"
}